language: python

stages:
- test
- name: deploy
  if: repo = ESSS/flask-restalchemy AND tag IS present

install:
- pip install -U pip
- pip install -U tox

script:
- tox

jobs:
  include:
  - python: '3.6'
    env: TOXENV=docs

  - python: '3.7'
    env: TOXENV=py37

  - python: '3.6'
    env: TOXENV=py36

  - python: '3.7'
    env: TOXENV=linting

  - stage: deploy
    python: '3.6'
    env:
    install: pip install -U setuptools setuptools_scm
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: loliveira
      password:
        secure: jowSR9tknuqoU0mQiB+xLWdg14SbdqdlI9eoPO0kgjF1NxrGGNUBwfETxjfez0WbNu25QCdd8BA6IkokyyjoN1Spp40n5SJpCKQzmSYFauNAQUIea68IIsBHGbZU85E+5sb1exqV1/A7f2XnjiEkako9z2twNcLEMfSTxjItxJLGOWLoPK9q61s3k43PQarZk5FcCRfDqd6gg1IWaJxgkAzXqSGsSVBD6131P6CfHGZBX93rjXaCcw0TsZs6o7nQ9xYMSd3K9/7uNqeeiRrsHoqYLWNx45k+vtboNxIiONDgtdgqF1ED/+u7259nfdg2kab77guJhZgGiBMmoBfCuBG9EWsjxD/8UbZXK78XpwgDMurgNpE7i02Rsl2N0ttkYjo0ei87du037WLfbp/DkcAgo65LJERrUxeB7DY0jv8SLciZ8yBCgkHZgLepXW55eO+jBbXjHDEs6SnCHBgZN2gTv0Ab71B5kkslL/dq43+Po/ZMPVCPvEwcEfGBgNQf1oPDJI523umZUkRLc/KF3sYG43G6Co7v4+EvVAXP7enW/gpdgxJRpD0phM25l0jJ+lB93iNud9lXO3unXjxkHImx0tKjz7Sbc9KOCxg/0EYNgMqe5SaVcrDhfMnsy1mH7UaLLT8YFnPJn/SH4gO358DRZe32+FrIiz/dBmffqkM=
      on:
        tags: true
        repo: ESSS/flask-restalchemy
        python: 3.6
branches:
  only:
  - master
  - "/^v(\\d+\\.)*\\d/"
