name: flask-restalchemy

dependencies:
  - python>=3.4
  - flask
  - sqlalchemy>=1.1
  - sqlalchemy-utils>=0.30
  - flask-restful>=0.3.0
  - flask-sqlalchemy>=2.3.0
  - pytest
  - pytest-datadir
  - pytest-mock>=1.10.0
  - tox


environment:
  PYTHONPATH:
    - {{ root }}/src
