name: flask-restalchemy

dependencies:
  - python>=3.5
  - flask>=1.0
  - sqlalchemy>=1.1
  - sqlalchemy-utils>=0.30
  - flask-sqlalchemy>=2.3.0
  - pytest
  - pytest-regeressions
  - pytest-mock>=1.10.0
  - tox


environment:
  PYTHONPATH:
    - {{ root }}/src
